### PR TITLE
add temp-dir volumes and volume mounts using emptyDir to console pods /tmp 

### PR DESCRIPTION
**Pull request by seemywingz**
## Test Plan

I tested these changes by deploying them to an existing console cluster in EKS

- [N/A ] If required, I have updated the Plural documentation accordingly.
- [√] I have added tests to cover my changes.
- I deployed these changes to an existing console deployment in EKS 
image
- [√] I have added a meaningful title and summary to convey the impact of this PR to a user.

### CODE REVIEW

**Review by michaeljguarino — COMMENTED** [review]
we should also wire this into the migration job I believe too

**Comment by seemywingz** [comment]
I added the `emptyDir` changes to the _migration job_ but this is an immutable object and needs to be delete before updating 
kubectl delete job console-migration-v2-842026a4 -n plrl-console

**Comment by michaeljguarino** [comment]
> I added the `emptyDir` changes to the _migration job_ but this is an immutable object and needs to be delete before updating
> 
> ```shell
> ▶ helm upgrade --install -f values.secret.yaml  console . -n plrl-console
> coalesce.go:237: warning: skipped value for console.extraSecretEnv: Not a table.
> coalesce.go:237: warning: skipped value for console.extraSecretEnv: Not a table.
> Error: UPGRADE FAILED: cannot patch "console-migration-v2-842026a4" with kind Job: Job.batch "console-migration-v2-842026a4" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"batch.kubernetes.io/controller-uid":"f24da89e-780a-4937-ab03-f8494e63bf94", "batch.kubernetes.io/job-name":"console-migration-v2-842026a4", "controller-uid":"f24da89e-780a-4937-ab03-f8494e63bf94", "job-name":"console-migration-v2-842026a4"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume{core.Volume{Name:"scratch", VolumeSource:core.VolumeSource{HostPath:(*core.HostPathVolumeSource)(nil), EmptyDir:(*core.EmptyDirVolumeSource)(0xc0111ef998), GCEPersistentDisk:(*core.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*core.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*core.GitRepoVolumeSource)(nil), Secret:(*core.SecretVolumeSource)(nil), NFS:(*core.NFSVolumeSource)(nil), ISCSI:(*core.ISCSIVolumeSource)(nil), Glusterfs:(*core.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*core.PersistentVolumeClaimVolumeSource)(nil), RBD:(*core.RBDVolumeSource)(nil), Quobyte:(*core.QuobyteVolumeSource)(nil), FlexVolume:(*core.FlexVolumeSource)(nil), Cinder:(*core.CinderVolumeSource)(nil), CephFS:(*core.CephFSVolumeSource)(nil), Flocker:(*core.FlockerVolumeSource)(nil), DownwardAPI:(*core.DownwardAPIVolumeSource)(nil), FC:(*core.FCVolumeSource)(nil), AzureFile:(*core.AzureFileVolumeSource)(nil), ConfigMap:(*core.ConfigMapVolumeSource)(nil), VsphereVolume:(*core.VsphereVirtualDiskVolumeSource)(nil), AzureDisk:(*core.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*core.PhotonPersistentDiskVolumeSource)(nil), Projected:(*core.ProjectedVolumeSource)(nil), PortworxVolume:(*core.PortworxVolumeSource)(nil), ScaleIO:(*core.ScaleIOVolumeSource)(nil), StorageOS:(*core.StorageOSVolumeSource)(nil), CSI:(*core.CSIVolumeSource)(nil), Ephemeral:(*core.EphemeralVolumeSource)(nil)}}, core.Volume{Name:"temp-dir", VolumeSource:core.VolumeSource{HostPath:(*core.HostPathVolumeSource)(nil), EmptyDir:(*core.EmptyDirVolumeSource)(0xc0111ef9b0), GCEPersistentDisk:(*core.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*core.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*core.GitRepoVolumeSource)(nil), Secret:(*core.SecretVolumeSource)(nil), NFS:(*core.NFSVolumeSource)(nil), ISCSI:(*core.ISCSIVolumeSource)(nil), Glusterfs:(*core.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*core.PersistentVolumeClaimVolumeSource)(nil), RBD:(*core.RBDVolumeSource)(nil), Quobyte:(*core.QuobyteVolumeSource)(nil), FlexVolume:(*core.FlexVolumeSource)(nil), Cinder:(*core.CinderVolumeSource)(nil), CephFS:(*core.CephFSVolumeSource)(nil), Flocker:(*core.FlockerVolumeSource)(nil), DownwardAPI:(*core.DownwardAPIVolumeSource)(nil), FC:(*core.FCVolumeSource)(nil), AzureFile:(*core.AzureFileVolumeSource)(nil), ConfigMap:(*core.ConfigMapVolumeSource)(nil), VsphereVolume:(*core.VsphereVirtualDiskVolumeSource)(nil), AzureDisk:(*core.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*core.PhotonPersistentDiskVolumeSource)(nil), Projected:(*core.ProjectedVolumeSource)(nil), PortworxVolume:(*core.PortworxVolumeSource)(nil), ScaleIO:(*core.ScaleIOVolumeSource)(nil), StorageOS:(*core.StorageOSVolumeSource)(nil), CSI:(*core.CSIVolumeSource)(nil), Ephemeral:(*core.EphemeralVolumeSource)(nil)}}}, InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"migrator", Image:"dkr.plural.sh/console/console:0.9.16", Command:[]string{"/opt/app/bin/console", "migrate"}, Args:[]string(nil), WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource{core.EnvFromSource{Prefix:"", ConfigMapRef:(*core.ConfigMapEnvSource)(nil), SecretRef:(*core.SecretEnvSource)(0xc0111efa28)}, core.EnvFromSource{Prefix:"", ConfigMapRef:(*core.ConfigMapEnvSource)(nil), SecretRef:(*core.SecretEnvSource)(0xc0111efa70)}}, Env:[]core.EnvVar{core.EnvVar{Name:"HOST", Value:"console.plrl.livingroom.cloud", ValueFrom:(*core.EnvVarSource)(nil)}, core.EnvVar{Name:"KAS_DNS", Value:"kas.plrl.livingroom.cloud", ValueFrom:(*core.EnvVarSource)(nil)}, core.EnvVar{Name:"NAMESPACE", Value:"", ValueFrom:(*core.EnvVarSource)(0xc0053786e0)}, core.EnvVar{Name:"POD_IP", Value:"", ValueFrom:(*core.EnvVarSource)(0xc005378720)}, core.EnvVar{Name:"REPLICAS", Value:"2", ValueFrom:(*core.EnvVarSource)(nil)}, core.EnvVar{Name:"POD_NAME", Value:"", ValueFrom:(*core.EnvVarSource)(0xc005378760)}, core.EnvVar{Name:"POSTGRES_URL", Value:"", ValueFrom:(*core.EnvVarSource)(0xc0053787c0)}}, Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil), Claims:[]core.ResourceClaim(nil)}, ResizePolicy:[]core.ContainerResizePolicy(nil), RestartPolicy:(*core.ContainerRestartPolicy)(nil), VolumeMounts:[]core.VolumeMount{core.VolumeMount{Name:"scratch", ReadOnly:false, MountPath:"/opt/app/var", SubPath:"", MountPropagation:(*core.MountPropagationMode)(nil), SubPathExpr:""}, core.VolumeMount{Name:"temp-dir", ReadOnly:false, MountPath:"/tmp", SubPath:"", MountPropagation:(*core.MountPropagationMode)(nil), SubPathExpr:""}}, VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), StartupProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]core.EphemeralContainer(nil), RestartPolicy:"Never", TerminationGracePeriodSeconds:(*int64)(0xc01b53a940), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"console", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc007e1b200), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", SetHostnameAsFQDN:(*bool)(nil), Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), PreemptionPolicy:(*core.PreemptionPolicy)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), Overhead:core.ResourceList(nil), EnableServiceLinks:(*bool)(nil), TopologySpreadConstraints:[]core.TopologySpreadConstraint(nil), OS:(*core.PodOS)(nil), SchedulingGates:[]core.PodSchedulingGate(nil), ResourceClaims:[]core.PodResourceClaim(nil)}}: field is immutable
> ```
> 
> It was successful after deleting the job
> 
> ```shell
> ⎈ plrl-console-kev-eks plrl-console
> console/charts/console  kevin-eng-1955-console-containers-should-use-emptydir-for-tmp-directory ✔ 
> ▶ kubectl delete job console-migration-v2-842026a4 -n plrl-console
> job.batch "console-migration-v2-842026a4" deleted
> 
> ⎈ plrl-console-kev-eks plrl-console
> console/charts/console  kevin-eng-1955-console-containers-should-use-emptydir-for-tmp-directory ✔ 
> ▶ helm upgrade --install -f values.secret.yaml  console . -n plrl-console
> coalesce.go:237: warning: skipped value for console.extraSecretEnv: Not a table.
> coalesce.go:237: warning: skipped value for console.extraSecretEnv: Not a table.
> Release "console" has been upgraded. Happy Helming!
> NAME: console
> LAST DEPLOYED: Mon Jun  3 13:11:05 2024
> NAMESPACE: plrl-console
> STATUS: deployed
> REVISION: 9
> TEST SUITE: None
> ```

The simple way to fix this is to rename the job itself so helm deletes any old one and recreates the new one.  This can be done by slightly changing the prefix (I know we already template in the image tag to force it to recreate for the same reason)

**Comment by seemywingz** [comment]
Would it make sense to add a random unique id to the job so it will be updated when making changes?
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: console-migration-v2-{{ .Values.image.tag | default .Chart.AppVersion | sha256sum | trunc 8 }}-{{ randAlphaNum 5 | lower }}
  labels:
    platform.plural.sh/ignore: 'true'
    {{ include "console.labels" . | nindent 4 }}
```
This will allow these changes to be made on existing console deployments without having to delete or rename the _migration job_

**Comment by michaeljguarino** [comment]
> Would it make sense to add a random unique id to the job so it will be updated when making changes?
> 
> ```yaml
> apiVersion: batch/v1
> kind: Job
> metadata:
>   name: console-migration-v2-{{ .Values.image.tag | default .Chart.AppVersion | sha256sum | trunc 8 }}-{{ randAlphaNum 5 | lower }}
>   labels:
>     platform.plural.sh/ignore: 'true'
>     {{ include "console.labels" . | nindent 4 }}
> ```
> 
> This will allow these changes to be made on existing console deployments without having to delete or rename the _migration job_

No it shouldn't be random because then it will recreate on each loop with the agent.  The existing pattern is right because it's deterministic but changes whenever the underlying code changes

**Review by michaeljguarino — APPROVED** [review]

**Pull request merged**
