### PR TITLE
feat: Added vitess and strimzi compatibility

### PR DESCRIPTION
**Pull request by smyja**
Added Vitess, a graduated CNCF project. https://github.com/planetscale/vitess-operator#compatibility
Added Strimzi, a CNCF project https://strimzi.io/downloads/

## Checklist

- [ ] If required, I have updated the Plural documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a meaningful title and summary to convey the impact of this PR to a user.

### CODE REVIEW

**Review by michaeljguarino — APPROVED** [review]
This is cool but the major postgres operators or strimzi kafka would actually be more useful for many companies

**Comment by smyja** [comment]
> This is cool but the major postgres operators or strimzi kafka would actually be more useful for many companies

I have added strimzi to this pr.

**Review by michaeljguarino — COMMENTED** [review]
strimzi is compatible w/ every k8s version?  I find that a bit hard to believe, could you link the doc?

**Comment by smyja** [comment]
> strimzi is compatible w/ every k8s version? I find that a bit hard to believe, could you link the doc?

https://strimzi.io/downloads/

**Review by michaeljguarino — APPROVED** [review]

**Pull request merged**
