### PR TITLE
feat: Services tree diagram

### PR DESCRIPTION
**Pull request by maciaszczykm**
Added services tree diagram to both services views. It displays connection between all services. All orphaned nodes are positioned in rows of three elements with the help of invisible edges.

Edit: Fixes PROD-2452.

Zrzut ekranu 2024-07-23 o 14 17 05
Zrzut ekranu 2024-07-23 o 14 18 13

### CODE REVIEW

**Comment by michaeljguarino** [comment]
@maciaszczykm Did you also account for the `parent` field on global services (this should also be able to link to the service that spawned the global service)

**Comment by michaeljguarino** [comment]
Also I definitely think this could use a full-screen view like we have for stacks

**Comment by maciaszczykm** [comment]
@michaeljguarino Added missing things and improvements. Now, It also fixes PROD-2452.

**Comment by michaeljguarino** [comment]
Cool cool, I'll give it another look

**Review by michaeljguarino — APPROVED** [review]
Looks great, let's merge it

**Pull request merged**
