### PR TITLE
fix: ensure that tokenSecretRef is set before getting secret

### PR DESCRIPTION
**Pull request by floreks**
- Added unit tests to cover basic scenarios

## Test Plan

Locally + unit tests

## Checklist

- [ ] If required, I have updated the Plural documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a meaningful title and summary to convey the impact of this PR to a user.

### CODE REVIEW

**Review by michaeljguarino — COMMENTED** [review]
will this requeue if the scm connection is not found and the tokenSecretRef also is not set?

**Comment by floreks** [comment]
> will this requeue if the scm connection is not found and the tokenSecretRef also is not set?

Since `tokenSecretRef` is optional, it will ignore it and create a ScmConnection in the console API without it.

**Comment by michaeljguarino** [comment]
> > will this requeue if the scm connection is not found and the tokenSecretRef also is not set?
> 
> Since `tokenSecretRef` is optional, it will ignore it and create a ScmConnection in the console API without it.

That's probably not the correct behavior, it should only try to create a ScmConnection if there is a token secret ref (a token is required), but assume if there isn't that it's going to be created outside the operator and requeue until it's created manually by the user.

**Comment by floreks** [comment]
@michaeljguarino I have updated the logic and added a unit test to cover this case.

**Review by michaeljguarino — APPROVED** [review]

**Pull request merged**
